name: Publish package to GitHub Packages
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup protoc
        run: bash install_buf.sh
      - name: buf check
        id: buf_check
        run: |
            exitcode=1
            echo "foo" > message.txt
            echo "##[set-output name=message;]$(cat message.txt)"
            echo "##[set-output name=status;]$(echo $exitcode)"
            echo ${{ steps.buf_check.outputs.message }}
            echo ${{ steps.buf_check.outputs.status }}
            exit 0
      # - if: steps.buf_check.outputs.status > 0
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.buf_check.outputs.message }}
          check_for_duplicate_msg: false  # OPTIONAL 
