name: Publish package to GitHub Packages
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup protoc
        run: ./install_buf.sh
      - name: buf check
        id: buf_check
        run: |
            ./buf check breaking --against-input 'https://github.com/stroeer/proto-ci-test.git#branch=master' --input-config buf.yaml > message.txt || true
            echo "::set-output name=message::$(cat message.txt)"
            echo "::set-output name=status::$(wc -l < message.txt)"
      - if: steps.buf_check.outputs.status != "0"
        name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.buf_check.outputs.message }}
          check_for_duplicate_msg: false  # OPTIONAL 
