name: buf check
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout pull_request
        uses: actions/checkout@v2
      - name: Setup buf
        run: ./install_buf.sh
      - name: buf check breaking
        run: ./buf check breaking --against-input 'https://github.com/stroeer/proto-ci-test.git#branch=master' --input-config buf.yaml