name: Publish package to GitHub Packages
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    container: bufbuild/buf
    steps:
      - name: docker login
        run: docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${{ github.actor }}
      - uses: actions/checkout@v2
      - name: buf check
        id: buf_check
        run: |
            buf check breaking --against-input 'https://github.com/stroeer/proto-ci-test.git#branch=master' --input-config buf.yaml > message.txt || true
            echo "::set-output name=message::$(cat message.txt)"
            if [ -s message.txt ]; then
              echo ::set-output name=failed::'true';
            fi
      - if: steps.buf_check.outputs.failed == 'true'
        name: comment PR
        uses: docker://docker.pkg.github.com/stroeer/comment-on-pr/github-action:1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ## :fire: Breaking Changes
            ```
            ${{ steps.buf_check.outputs.message }}
            ```
          check_for_duplicate_msg: false
      - if: steps.buf_check.outputs.failed != 'true'
        name: comment PR
        uses: docker://docker.pkg.github.com/stroeer/comment-on-pr/github-action:1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ## :white_check_mark: No Breaking Changes
          check_for_duplicate_msg: false
